[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "node_modules/.bin/prisma migrate deploy"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
