[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "node prisma-cli/node_modules/prisma/build/index.js migrate deploy"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
