import { test, expect, type Page } from '@playwright/test'

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// PHASE 3 STEP 10 — Student Portal Shell
// Verifies the portal dashboard shell: requireStudent() redirects non-students,
// zero-enrollment students see an empty state, the profile page renders
// read-only student + parent data. Single-enrollment inline materials and
// multi-enrollment cards are covered separately.
// Requires: dev server on localhost:3000, seeded admin user. Creates the
// students it needs via the admin UI (no direct DB access).
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const BASE = 'http://localhost:3000'
const ADMIN_EMAIL = 'jozo@udruga-inovatic.hr'
const ADMIN_PASSWORD = 'admin123'

const RUN_ID = Date.now().toString().slice(-6)

const ZERO_STUDENT = {
  firstName: `Pero`,
  lastName: `NulaUpisa${RUN_ID}`,
  dateOfBirth: '2015-06-15',
  childSchool: 'OŠ Marjan',
  parentName: `Mate NulaUpisa ${RUN_ID}`,
  parentEmail: `mate.nulaupisa.${RUN_ID}@test.com`,
  parentPhone: '0911111111',
}

// Populated by beforeAll — credentials generated by the admin create flow.
let zeroCredentials: { username: string; password: string; loginEmail: string } | null = null

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function loginAsAdmin(page: Page) {
  await page.goto(`${BASE}/prijava`)
  await page.locator('#identifier').fill(ADMIN_EMAIL)
  await page.locator('input[type="password"]').fill(ADMIN_PASSWORD)
  await page.locator('button[type="submit"]').click()
  await page.waitForURL(`${BASE}/admin`, { timeout: 30000 })
  await page.waitForLoadState('networkidle')
}

async function loginWithEmail(page: Page, email: string, password: string) {
  await page.goto(`${BASE}/prijava`)
  await page.locator('#identifier').fill(email)
  await page.locator('input[type="password"]').fill(password)
  await page.locator('button[type="submit"]').click()
  await page.waitForLoadState('networkidle')
}

async function createZeroEnrollmentStudent(page: Page): Promise<{ username: string; password: string }> {
  await loginAsAdmin(page)
  await page.goto(`${BASE}/admin/ucenici`)
  await page.getByRole('button', { name: 'Kreiraj učenika' }).click()

  await page.locator('#create-student-first').fill(ZERO_STUDENT.firstName)
  await page.locator('#create-student-last').fill(ZERO_STUDENT.lastName)
  await page.locator('#create-student-dob').fill(ZERO_STUDENT.dateOfBirth)
  await page.locator('#create-student-school').fill(ZERO_STUDENT.childSchool)
  await page.locator('#create-student-parent-name').fill(ZERO_STUDENT.parentName)
  await page.locator('#create-student-parent-email').fill(ZERO_STUDENT.parentEmail)
  await page.locator('#create-student-parent-phone').fill(ZERO_STUDENT.parentPhone)

  const dialog = page.locator('[role="dialog"]')
  await dialog.getByRole('button', { name: 'Kreiraj učenika' }).click()
  await expect(dialog.getByText('Učenik kreiran')).toBeVisible({ timeout: 10000 })

  // The credentials block renders two <p> elements with leading label spans.
  // We parse "Korisničko ime: X" / "Lozinka: Y" from their text content.
  const usernameText = (await dialog.locator('p', { hasText: 'Korisničko ime:' }).innerText()).trim()
  const passwordText = (await dialog.locator('p', { hasText: 'Lozinka:' }).innerText()).trim()
  const username = usernameText.replace(/^Korisničko ime:\s*/, '').trim()
  const password = passwordText.replace(/^Lozinka:\s*/, '').trim()

  if (!username || !password) {
    throw new Error(`Could not parse credentials: ${usernameText} / ${passwordText}`)
  }
  return { username, password }
}

// ─── Test suite ──────────────────────────────────────────────────────────────

test.describe.configure({ mode: 'serial' })

test.describe('Phase 3 Step 10 — Student Portal Shell', () => {
  test.beforeAll(async ({ browser }) => {
    test.setTimeout(120000)
    const page = await browser.newPage()
    const creds = await createZeroEnrollmentStudent(page)
    zeroCredentials = {
      ...creds,
      loginEmail: `${creds.username}@student.inovatic.local`,
    }
    await page.close()
  })

  // ── Redirects ──────────────────────────────────────────────────────────────

  test('unauthenticated visitor is redirected from /portal to /prijava', async ({ page }) => {
    await page.goto(`${BASE}/portal`)
    await page.waitForURL(/\/prijava/, { timeout: 15000 })
    expect(page.url()).toContain('/prijava')
  })

  test('admin on /portal is redirected by requireStudent() guard', async ({ page }) => {
    await loginAsAdmin(page)
    await page.goto(`${BASE}/portal`)
    await page.waitForURL(/\/prijava/, { timeout: 15000 })
    expect(page.url()).toContain('/prijava')
  })

  // ── Zero-enrollment experience ─────────────────────────────────────────────

  test('zero-enrollment student lands on empty state with Croatian copy', async ({ page }) => {
    if (!zeroCredentials) throw new Error('zero-enrollment student not seeded')
    await loginWithEmail(page, zeroCredentials.loginEmail, zeroCredentials.password)
    await page.waitForURL(/\/portal/, { timeout: 15000 })

    await expect(page.getByRole('heading', { name: 'Dobrodošli' })).toBeVisible()
    await expect(page.getByText(/Nemate aktivnih upisa\. Obratite se administratoru\./)).toBeVisible()

    // No group cards should be rendered in the empty state.
    await expect(page.getByRole('heading', { name: 'Moje grupe' })).toHaveCount(0)
  })

  test('zero-enrollment student sees their profile read-only with parent info', async ({ page }) => {
    if (!zeroCredentials) throw new Error('zero-enrollment student not seeded')
    await loginWithEmail(page, zeroCredentials.loginEmail, zeroCredentials.password)
    await page.waitForURL(/\/portal/, { timeout: 15000 })
    await page.goto(`${BASE}/portal/profil`)

    await expect(
      page.getByRole('heading', { name: `${ZERO_STUDENT.firstName} ${ZERO_STUDENT.lastName}` }),
    ).toBeVisible()

    // Student section fields render.
    await expect(page.getByText('Korisničko ime', { exact: true })).toBeVisible()
    await expect(page.getByText(zeroCredentials.username, { exact: true })).toBeVisible()
    await expect(page.getByText(ZERO_STUDENT.childSchool)).toBeVisible()

    // Parent section.
    await expect(page.getByText('Roditelj / skrbnik')).toBeVisible()
    await expect(page.getByText(ZERO_STUDENT.parentName)).toBeVisible()
    await expect(page.getByText(ZERO_STUDENT.parentEmail)).toBeVisible()
    await expect(page.getByText(ZERO_STUDENT.parentPhone)).toBeVisible()

    // No edit affordance should be present on the profile page.
    await expect(page.getByRole('button', { name: /Uredi|Spremi/ })).toHaveCount(0)
  })

  test('student portal does NOT expose comment/grade UI (internal-staff-only leakage guard)', async ({ page }) => {
    if (!zeroCredentials) throw new Error('zero-enrollment student not seeded')
    await loginWithEmail(page, zeroCredentials.loginEmail, zeroCredentials.password)
    await page.waitForURL(/\/portal/, { timeout: 15000 })

    // Body should not contain any of the staff-only terminology.
    const body = (await page.locator('body').innerText()).toLowerCase()
    expect(body).not.toContain('komentar')
    expect(body).not.toContain('bilješk')
    expect(body).not.toContain('recenzij')
    expect(body).not.toContain('ocjen')
  })
})
